baseURL = "https://danielcorin.com/"
languageCode = "en-us"
theme = "poison"
pluralizelisttitles = false
title = "Way Enough"
enableRobotsTXT = true
staticDir = ['static', '_static']

[params.author]
name = "Dan Corin"
email = "dcorin6@gmail.com"

[params]
brand = "Way Enough" # appears in the sidebar
description = "Mostly software stuff"
dark_mode = true
rss_icon = true
paginate = 10
front_page_content = ["posts", "til"]

# MENU PLACEHOLDER
# Menu dict keys:
# Name:         The name to display on the menu.
# URL:          The directory relative to the content directory.
# HasChildren:  If the directory's files should be listed.  Default is true.
# Limit:        If the files should be listed, how many should be shown.
menu = [
    { Name = "ğŸ“– Posts", URL = "/posts/", Pre = "Recent", HasChildren = false },
    { Name = "ğŸ“ Today I Learned", URL = "/til/", HasChildren = false },
    { Name = "âœï¸ Logs", URL = "/logs/", HasChildren = false },
    { Name = "ğŸ‘‹ About", URL = "/about/", HasChildren = false },
    { Name = "ğŸ—ï¸ Projects", URL = "/projects/" },
    { Name = "ğŸŒ± Garden", URL = "/garden/", HasChildren = false },
    { Name = "ğŸ’» Uses", URL = "/uses/", HasChildren = false },
    { Name = "ğŸ“ Now", URL = "/now/", HasChildren = false },
]

# Links to your socials.
email_url = "mailto://dcorin6@gmail.com"
twitter_url = "https://twitter.com/danielcorin1"
github_url = "https://github.com/danielcorin"
keybase_url = "https://keybase.io/danielcorin/"
linkedin_url = "https://www.linkedin.com/in/danielcorin/"
stackoverflow_url = "https://stackoverflow.com/users/2631732/daniel-corin"

[taxonomies]
series = "series"
tags = "tags"

[markup]
[markup.goldmark]
[markup.goldmark.renderer]
unsafe = true

[outputs]
home = ["HTML", "RSS"]
